



-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'COMPANIES'
-- 
-- ---

DROP TABLE IF EXISTS `COMPANIES`;
		
CREATE TABLE `COMPANIES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COUNTRY_ID` INTEGER NOT NULL,
  `STATE_ID` INTEGER NOT NULL,
  `CITY_ID` INTEGER NOT NULL,
  `REGISTRATION` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'USERS'
-- 
-- ---

DROP TABLE IF EXISTS `USERS`;
		
CREATE TABLE `USERS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'ROLES'
-- 
-- ---

DROP TABLE IF EXISTS `ROLES`;
		
CREATE TABLE `ROLES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'CATALOGS'
-- 
-- ---

DROP TABLE IF EXISTS `CATALOGS`;
		
CREATE TABLE `CATALOGS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'CATEGORIES'
-- 
-- ---

DROP TABLE IF EXISTS `CATEGORIES`;
		
CREATE TABLE `CATEGORIES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'PRODUCTS'
-- 
-- ---

DROP TABLE IF EXISTS `PRODUCTS`;
		
CREATE TABLE `PRODUCTS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'FILTERS'
-- 
-- ---

DROP TABLE IF EXISTS `FILTERS`;
		
CREATE TABLE `FILTERS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'ROLES_USERS'
-- 
-- ---

DROP TABLE IF EXISTS `ROLES_USERS`;
		
CREATE TABLE `ROLES_USERS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `ROLE_ID` INTEGER NOT NULL,
  `USER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'CATEGORY_PRODUCTS'
-- 
-- ---

DROP TABLE IF EXISTS `CATEGORY_PRODUCTS`;
		
CREATE TABLE `CATEGORY_PRODUCTS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` INTEGER NOT NULL,
  `PRODUCT_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'FILTERS_CATEGORIES'
-- 
-- ---

DROP TABLE IF EXISTS `FILTERS_CATEGORIES`;
		
CREATE TABLE `FILTERS_CATEGORIES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `FILTER_ID` INTEGER NOT NULL,
  `CATEGORY_ID` INTEGER NOT NULL,
  `SORT` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'FILTER_OPTIONS'
-- 
-- ---

DROP TABLE IF EXISTS `FILTER_OPTIONS`;
		
CREATE TABLE `FILTER_OPTIONS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `FILTER_ID` INTEGER NOT NULL,
  `SORT` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'FILTER_OPTIONS_PRODUCTS'
-- 
-- ---

DROP TABLE IF EXISTS `FILTER_OPTIONS_PRODUCTS`;
		
CREATE TABLE `FILTER_OPTIONS_PRODUCTS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `FILTER_OPTION_ID` INTEGER NOT NULL,
  `PRODUCT_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'GROUPS'
-- 
-- ---

DROP TABLE IF EXISTS `GROUPS`;
		
CREATE TABLE `GROUPS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'GROUPS_USERS'
-- 
-- ---

DROP TABLE IF EXISTS `GROUPS_USERS`;
		
CREATE TABLE `GROUPS_USERS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `GROUP_ID` INTEGER NOT NULL,
  `USER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'COUNTRY'
-- 
-- ---

DROP TABLE IF EXISTS `COUNTRY`;
		
CREATE TABLE `COUNTRY` (
  `ID` INTEGER NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'STATE'
-- 
-- ---

DROP TABLE IF EXISTS `STATE`;
		
CREATE TABLE `STATE` (
  `ID` INTEGER NOT NULL,
  `COUNTRY_ID` INTEGER NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'CITY'
-- 
-- ---

DROP TABLE IF EXISTS `CITY`;
		
CREATE TABLE `CITY` (
  `ID` INTEGER NOT NULL,
  `COUNTRY_ID` INTEGER NOT NULL,
  `STATE_ID` INTEGER NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'RIGHTS'
-- 
-- ---

DROP TABLE IF EXISTS `RIGHTS`;
		
CREATE TABLE `RIGHTS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'RIGHT_ASSIGNMENTS'
-- 
-- ---

DROP TABLE IF EXISTS `RIGHT_ASSIGNMENTS`;
		
CREATE TABLE `RIGHT_ASSIGNMENTS` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `RIGHT_ID` INTEGER NOT NULL,
  `SUBJECT_ID` INTEGER NOT NULL,
  `SUBJECT_TYPE` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'CATALOG_CATEGORIES'
-- 
-- ---

DROP TABLE IF EXISTS `CATALOG_CATEGORIES`;
		
CREATE TABLE `CATALOG_CATEGORIES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `CATALOG_ID` INTEGER NOT NULL,
  `CATEGORY_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'IMAGES'
-- 
-- ---

DROP TABLE IF EXISTS `IMAGES`;
		
CREATE TABLE `IMAGES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` INTEGER NOT NULL,
  `SRC` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Table 'PRODUCT_IMAGES'
-- 
-- ---

DROP TABLE IF EXISTS `PRODUCT_IMAGES`;
		
CREATE TABLE `PRODUCT_IMAGES` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INTEGER NOT NULL,
  `IMAGE_ID` INTEGER NOT NULL,
  PRIMARY KEY (`ID`)
);

-- ---
-- Foreign Keys 
-- ---

ALTER TABLE `COMPANIES` ADD FOREIGN KEY (COUNTRY_ID) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `COMPANIES` ADD FOREIGN KEY (STATE_ID) REFERENCES `STATE` (`ID`);
ALTER TABLE `COMPANIES` ADD FOREIGN KEY (CITY_ID) REFERENCES `CITY` (`ID`);
ALTER TABLE `USERS` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `ROLES` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `CATALOGS` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `CATEGORIES` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `PRODUCTS` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `FILTERS` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `ROLES_USERS` ADD FOREIGN KEY (ROLE_ID) REFERENCES `ROLES` (`ID`);
ALTER TABLE `ROLES_USERS` ADD FOREIGN KEY (USER_ID) REFERENCES `USERS` (`ID`);
ALTER TABLE `CATEGORY_PRODUCTS` ADD FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (`ID`);
ALTER TABLE `CATEGORY_PRODUCTS` ADD FOREIGN KEY (PRODUCT_ID) REFERENCES `PRODUCTS` (`ID`);
ALTER TABLE `FILTERS_CATEGORIES` ADD FOREIGN KEY (FILTER_ID) REFERENCES `FILTERS` (`ID`);
ALTER TABLE `FILTERS_CATEGORIES` ADD FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (`ID`);
ALTER TABLE `FILTER_OPTIONS` ADD FOREIGN KEY (FILTER_ID) REFERENCES `FILTERS` (`ID`);
ALTER TABLE `FILTER_OPTIONS_PRODUCTS` ADD FOREIGN KEY (FILTER_OPTION_ID) REFERENCES `FILTER_OPTIONS` (`ID`);
ALTER TABLE `FILTER_OPTIONS_PRODUCTS` ADD FOREIGN KEY (PRODUCT_ID) REFERENCES `PRODUCTS` (`ID`);
ALTER TABLE `GROUPS` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `GROUPS_USERS` ADD FOREIGN KEY (GROUP_ID) REFERENCES `GROUPS` (`ID`);
ALTER TABLE `GROUPS_USERS` ADD FOREIGN KEY (USER_ID) REFERENCES `USERS` (`ID`);
ALTER TABLE `STATE` ADD FOREIGN KEY (COUNTRY_ID) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `CITY` ADD FOREIGN KEY (COUNTRY_ID) REFERENCES `COUNTRY` (`ID`);
ALTER TABLE `CITY` ADD FOREIGN KEY (STATE_ID) REFERENCES `STATE` (`ID`);
ALTER TABLE `RIGHTS` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `RIGHT_ASSIGNMENTS` ADD FOREIGN KEY (RIGHT_ID) REFERENCES `RIGHTS` (`ID`);
ALTER TABLE `RIGHT_ASSIGNMENTS` ADD FOREIGN KEY (SUBJECT_ID) REFERENCES `GROUPS` (`ID`);
ALTER TABLE `RIGHT_ASSIGNMENTS` ADD FOREIGN KEY (SUBJECT_ID) REFERENCES `ROLES` (`ID`);
ALTER TABLE `RIGHT_ASSIGNMENTS` ADD FOREIGN KEY (SUBJECT_ID) REFERENCES `USERS` (`ID`);
ALTER TABLE `CATALOG_CATEGORIES` ADD FOREIGN KEY (CATALOG_ID) REFERENCES `CATALOGS` (`ID`);
ALTER TABLE `CATALOG_CATEGORIES` ADD FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (`ID`);
ALTER TABLE `IMAGES` ADD FOREIGN KEY (COMPANY_ID) REFERENCES `COMPANIES` (`ID`);
ALTER TABLE `PRODUCT_IMAGES` ADD FOREIGN KEY (PRODUCT_ID) REFERENCES `PRODUCTS` (`ID`);
ALTER TABLE `PRODUCT_IMAGES` ADD FOREIGN KEY (IMAGE_ID) REFERENCES `IMAGES` (`ID`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `COMPANIES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `USERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ROLES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CATALOGS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CATEGORIES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PRODUCTS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `FILTERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `ROLES_USERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CATEGORY_PRODUCTS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `FILTERS_CATEGORIES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `FILTER_OPTIONS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `FILTER_OPTIONS_PRODUCTS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `GROUPS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `GROUPS_USERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `COUNTRY` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `STATE` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CITY` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `RIGHTS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `RIGHT_ASSIGNMENTS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `CATALOG_CATEGORIES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `IMAGES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `PRODUCT_IMAGES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `COMPANIES` (`ID`,`COUNTRY_ID`,`STATE_ID`,`CITY_ID`,`REGISTRATION`) VALUES
-- ('','','','','');
-- INSERT INTO `USERS` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `ROLES` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `CATALOGS` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `CATEGORIES` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `PRODUCTS` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `FILTERS` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `ROLES_USERS` (`ID`,`ROLE_ID`,`USER_ID`) VALUES
-- ('','','');
-- INSERT INTO `CATEGORY_PRODUCTS` (`ID`,`CATEGORY_ID`,`PRODUCT_ID`) VALUES
-- ('','','');
-- INSERT INTO `FILTERS_CATEGORIES` (`ID`,`FILTER_ID`,`CATEGORY_ID`,`SORT`) VALUES
-- ('','','','');
-- INSERT INTO `FILTER_OPTIONS` (`ID`,`FILTER_ID`,`SORT`) VALUES
-- ('','','');
-- INSERT INTO `FILTER_OPTIONS_PRODUCTS` (`ID`,`FILTER_OPTION_ID`,`PRODUCT_ID`) VALUES
-- ('','','');
-- INSERT INTO `GROUPS` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `GROUPS_USERS` (`ID`,`GROUP_ID`,`USER_ID`) VALUES
-- ('','','');
-- INSERT INTO `COUNTRY` (`ID`,`NAME`) VALUES
-- ('','');
-- INSERT INTO `STATE` (`ID`,`COUNTRY_ID`,`NAME`) VALUES
-- ('','','');
-- INSERT INTO `CITY` (`ID`,`COUNTRY_ID`,`STATE_ID`,`NAME`) VALUES
-- ('','','','');
-- INSERT INTO `RIGHTS` (`ID`,`COMPANY_ID`) VALUES
-- ('','');
-- INSERT INTO `RIGHT_ASSIGNMENTS` (`ID`,`RIGHT_ID`,`SUBJECT_ID`,`SUBJECT_TYPE`) VALUES
-- ('','','','');
-- INSERT INTO `CATALOG_CATEGORIES` (`ID`,`CATALOG_ID`,`CATEGORY_ID`) VALUES
-- ('','','');
-- INSERT INTO `IMAGES` (`ID`,`COMPANY_ID`,`SRC`) VALUES
-- ('','','');
-- INSERT INTO `PRODUCT_IMAGES` (`ID`,`PRODUCT_ID`,`IMAGE_ID`) VALUES
-- ('','','');

